apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  project: spof-cluster
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 1.16.1
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/values.yaml
    - repoURL: 'https://github.com/SP0Fs/argo-cd-k8s.git'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true